//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsParser.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase, JsParser.Core.Infrastructure.ISettings {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarksData {
            get {
                return ((string)(this["BookmarksData"]));
            }
            set {
                this["BookmarksData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SortingEnabled {
            get {
                return ((bool)(this["SortingEnabled"]));
            }
            set {
                this["SortingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HierarchyEnabled {
            get {
                return ((bool)(this["HierarchyEnabled"]));
            }
            set {
                this["HierarchyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLineNumbersEnabled {
            get {
                return ((bool)(this["ShowLineNumbersEnabled"]));
            }
            set {
                this["ShowLineNumbersEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterByMarksEnabled {
            get {
                return ((bool)(this["FilterByMarksEnabled"]));
            }
            set {
                this["FilterByMarksEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>js</string>
  <string>asp</string>
  <string>aspx</string>
  <string>ascx</string>
  <string>html</string>
  <string>htm</string>
  <string>axd</string>
  <string>cshtml</string>
  <string>master</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Extensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Extensions"]));
            }
            set {
                this["Extensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrackActiveItem {
            get {
                return ((bool)(this["TrackActiveItem"]));
            }
            set {
                this["TrackActiveItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoExpandAll {
            get {
                return ((bool)(this["AutoExpandAll"]));
            }
            set {
                this["AutoExpandAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visible {
            get {
                return ((bool)(this["Visible"]));
            }
            set {
                this["Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font taggedFunction1Font {
            get {
                return ((global::System.Drawing.Font)(this["taggedFunction1Font"]));
            }
            set {
                this["taggedFunction1Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font taggedFunction2Font {
            get {
                return ((global::System.Drawing.Font)(this["taggedFunction2Font"]));
            }
            set {
                this["taggedFunction2Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font taggedFunction3Font {
            get {
                return ((global::System.Drawing.Font)(this["taggedFunction3Font"]));
            }
            set {
                this["taggedFunction3Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font taggedFunction4Font {
            get {
                return ((global::System.Drawing.Font)(this["taggedFunction4Font"]));
            }
            set {
                this["taggedFunction4Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font taggedFunction5Font {
            get {
                return ((global::System.Drawing.Font)(this["taggedFunction5Font"]));
            }
            set {
                this["taggedFunction5Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font taggedFunction6Font {
            get {
                return ((global::System.Drawing.Font)(this["taggedFunction6Font"]));
            }
            set {
                this["taggedFunction6Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color taggedFunction1Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction1Color"]));
            }
            set {
                this["taggedFunction1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color taggedFunction2Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction2Color"]));
            }
            set {
                this["taggedFunction2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color taggedFunction3Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction3Color"]));
            }
            set {
                this["taggedFunction3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color taggedFunction4Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction4Color"]));
            }
            set {
                this["taggedFunction4Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color taggedFunction5Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction5Color"]));
            }
            set {
                this["taggedFunction5Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color taggedFunction6Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction6Color"]));
            }
            set {
                this["taggedFunction6Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MaxParametersLength {
            get {
                return ((int)(this["MaxParametersLength"]));
            }
            set {
                this["MaxParametersLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MaxParametersLengthInFunctionChain {
            get {
                return ((int)(this["MaxParametersLengthInFunctionChain"]));
            }
            set {
                this["MaxParametersLengthInFunctionChain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Statistics {
            get {
                return ((string)(this["Statistics"]));
            }
            set {
                this["Statistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://apps.megaboich.com/statistics/jsparser/submit")]
        public string StatisticsServerUrl {
            get {
                return ((string)(this["StatisticsServerUrl"]));
            }
            set {
                this["StatisticsServerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendStatistics {
            get {
                return ((bool)(this["SendStatistics"]));
            }
            set {
                this["SendStatistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideAnonymousFunctions {
            get {
                return ((bool)(this["HideAnonymousFunctions"]));
            }
            set {
                this["HideAnonymousFunctions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ask")]
        public string SendStatisticsPolitic {
            get {
                return ((string)(this["SendStatisticsPolitic"]));
            }
            set {
                this["SendStatisticsPolitic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToDoListCollapsed {
            get {
                return ((bool)(this["ToDoListCollapsed"]));
            }
            set {
                this["ToDoListCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ToDoListLastHeight {
            get {
                return ((int)(this["ToDoListLastHeight"]));
            }
            set {
                this["ToDoListLastHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseVSColorTheme {
            get {
                return ((bool)(this["UseVSColorTheme"]));
            }
            set {
                this["UseVSColorTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>js</string>\r\n  <string>axd</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection JSExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["JSExtensions"]));
            }
            set {
                this["JSExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FixAspNetTags {
            get {
                return ((bool)(this["FixAspNetTags"]));
            }
            set {
                this["FixAspNetTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FixRazorSyntax {
            get {
                return ((bool)(this["FixRazorSyntax"]));
            }
            set {
                this["FixRazorSyntax"] = value;
            }
        }
    }
}
