//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using JsParser.Core.Parsers;

namespace JsParser.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase, IJavascriptParserSettings {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileSpecificData {
            get {
                return ((string)(this["FileSpecificData"]));
            }
            set {
                this["FileSpecificData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SortingEnabled {
            get {
                return ((bool)(this["SortingEnabled"]));
            }
            set {
                this["SortingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HierarchyEnabled {
            get {
                return ((bool)(this["HierarchyEnabled"]));
            }
            set {
                this["HierarchyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLineNumbersEnabled {
            get {
                return ((bool)(this["ShowLineNumbersEnabled"]));
            }
            set {
                this["ShowLineNumbersEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterByMarksEnabled {
            get {
                return ((bool)(this["FilterByMarksEnabled"]));
            }
            set {
                this["FilterByMarksEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>js</string>\r\n  <string>html</string>\r\n  <string>htm</string>\r\n</ArrayOfStr" +
            "ing>")]
        public global::System.Collections.Specialized.StringCollection Extensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Extensions"]));
            }
            set {
                this["Extensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrackActiveItem {
            get {
                return ((bool)(this["TrackActiveItem"]));
            }
            set {
                this["TrackActiveItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoExpandAll {
            get {
                return ((bool)(this["AutoExpandAll"]));
            }
            set {
                this["AutoExpandAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Visible {
            get {
                return ((bool)(this["Visible"]));
            }
            set {
                this["Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font TreeFont {
            get {
                return ((global::System.Drawing.Font)(this["TreeFont"]));
            }
            set {
                this["TreeFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color taggedFunction2Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction2Color"]));
            }
            set {
                this["taggedFunction2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color taggedFunction3Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction3Color"]));
            }
            set {
                this["taggedFunction3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color taggedFunction4Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction4Color"]));
            }
            set {
                this["taggedFunction4Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color taggedFunction5Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction5Color"]));
            }
            set {
                this["taggedFunction5Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color taggedFunction6Color {
            get {
                return ((global::System.Drawing.Color)(this["taggedFunction6Color"]));
            }
            set {
                this["taggedFunction6Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MaxParametersLength {
            get {
                return ((int)(this["MaxParametersLength"]));
            }
            set {
                this["MaxParametersLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MaxParametersLengthInFunctionChain {
            get {
                return ((int)(this["MaxParametersLengthInFunctionChain"]));
            }
            set {
                this["MaxParametersLengthInFunctionChain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Statistics {
            get {
                return ((string)(this["Statistics"]));
            }
            set {
                this["Statistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SendStatistics {
            get {
                return ((bool)(this["SendStatistics"]));
            }
            set {
                this["SendStatistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideAnonymousFunctions {
            get {
                return ((bool)(this["HideAnonymousFunctions"]));
            }
            set {
                this["HideAnonymousFunctions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ask")]
        public string SendStatisticsPolitic {
            get {
                return ((string)(this["SendStatisticsPolitic"]));
            }
            set {
                this["SendStatisticsPolitic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToDoListCollapsed {
            get {
                return ((bool)(this["ToDoListCollapsed"]));
            }
            set {
                this["ToDoListCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ToDoListLastHeight {
            get {
                return ((int)(this["ToDoListLastHeight"]));
            }
            set {
                this["ToDoListLastHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseVSColorTheme {
            get {
                return ((bool)(this["UseVSColorTheme"]));
            }
            set {
                this["UseVSColorTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScriptStripEnabled {
            get {
                return ((bool)(this["ScriptStripEnabled"]));
            }
            set {
                this["ScriptStripEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FixAspNetTags {
            get {
                return ((bool)(this["FixAspNetTags"]));
            }
            set {
                this["FixAspNetTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FixRazorSyntax {
            get {
                return ((bool)(this["FixRazorSyntax"]));
            }
            set {
                this["FixRazorSyntax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>TODO:</string>\r\n  <string>To Do:</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ToDoKeywords {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ToDoKeywords"]));
            }
            set {
                this["ToDoKeywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowErrorsNotificationOnTopOfEditor {
            get {
                return ((bool)(this["ShowErrorsNotificationOnTopOfEditor"]));
            }
            set {
                this["ShowErrorsNotificationOnTopOfEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>html</string>\r\n  <string>htm</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ScriptStripExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ScriptStripExtensions"]));
            }
            set {
                this["ScriptStripExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>asp</string>
  <string>aspx</string>
  <string>ascx</string>
  <string>master</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FixAspNetTagsExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FixAspNetTagsExtensions"]));
            }
            set {
                this["FixAspNetTagsExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>cshtml</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FixRazorSyntaxExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FixRazorSyntaxExtensions"]));
            }
            set {
                this["FixRazorSyntaxExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThemeSettingsSerialized {
            get {
                return ((string)(this["ThemeSettingsSerialized"]));
            }
            set {
                this["ThemeSettingsSerialized"] = value;
            }
        }
    }
}
